# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_urltoscrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltoscrape',
            name='actual_url',
            field=models.CharField(default='empty_url', max_length=200),
            preserve_default=False,
        ),
    ]
